permalink: /:year/:month/:day/:title.html
url: "http://dynamicprogrammer.com"
blog_url: "http://blog.dynamicprogrammer.com"
projects_url: "http://github.com/hgarcia"
music_url: "http://www.acidplanet.com/artist.asp?songs=292536&amp;t=4858"
rss_url: "http://feeds.feedburner.com/TheDynamicProgrammer"
author: "Hernan Garcia"
name: "The Dynamic Programmer"
destination: ../heroku/_site/